services:
  postgres:
    image: postgres:15
    container_name: ms-bank-db
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./ms-transaction/init.sql:/docker-entrypoint-initdb.d/init.sql

  ms-dao:
    build: ./ms-dao
    container_name: ms-dao
    env_file:
      - .env.db
      - ./ms-dao/.env.db
    ports:
      - "3200:3200"
    depends_on:
      - postgres

  ms-transaction:
    build: ./ms-transaction
    container_name: ms-transaction
    env_file:
      - .env.db
      - ./ms-transaction/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - ms-balance

  ms-balance:
    build: ./ms-balance
    container_name: ms-balance
    env_file:
      - .env.db
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"


volumes:
  pgdata:
