version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ms-bank-db
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  ms-transaction:
    build: ./ms-transaction
    container_name: ms-transaction
    env_file:
      - .env.db
      - ./ms-transaction/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - ms-balance

  ms-balance:
    build: ./ms-balance
    container_name: ms-balance
    env_file:
      - .env.db
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata:
